#!/bin/sh

#
# $Id$
#

#
# Configure these paths for your system.
#
SBCL=/usr/local/bin/sbcl
CMUCL=/usr/local/bin/lisp
ACL=/homedir/brg/aic/allegro-cl-amd64-linux/8.2/alisp
CCL=/usr/local/bin/ccl

# Setting this to "T" turns on the debug flag, adding a lot of
# checking and printing to the code. Generally don't do this in a
# production version.
DEBUG=NIL

usage()
{
echo "
  Usage: `basename $0` [-d] <platform>

  where platform is one of:

	sbcl	-- Steel Bank Common Lisp ($SBCL)

	ccl	-- Clozure Common Lisp ($CCL)

	cmucl	-- CMU Common Lisp ($CMUCL)

	acl	-- Allegro Common Lisp (ANSI Version) ($ACL)

  (If the above paths aren't correct, they should be set at the beginning
  of the file $0).

  If -d is given, build a debugging version of Garnet.
"
}

case $# in
    1)
	DEBUG=NIL
	;;
    2)
	if [ X"$1" = X"-d" ]; then
	    DEBUG=T
	    shift;
	else
	    usage;
	    exit 1
	fi
	;;
    *)
	usage;
	exit 1
	;;
esac
    
case $1 in
    sbcl)
	BUILD="$SBCL --disable-debugger"
	LOAD=$SBCL
	QUIT="(quit)"
	IMAGE=garnet-sbcl
	;;
    ccl)
	BUILD="$CCL --batch"
	LOAD=$CCL
	QUIT="(quit)"
	IMAGE=garnet-ccl
	;;
    cmucl)
	BUILD="$CMUCL -noinit -batch"
	LOAD="$CMUCL -noinit"
	QUIT="(quit)"
	IMAGE=garnet-cmucl
	;;
    acl)
	BUILD="$ACL -batch -backtrace-on-error"
	LOAD=$ACL
	QUIT="(exit)"
	IMAGE=garnet.dxl
	;;
    *)
	usage;
	exit 1
	;;
esac


$BUILD << EOF
(require :clx)
(load "garnet-prepare-compile")
(defvar Garnet-Garnet-Debug $DEBUG)
;;#+cmu (setf c:*record-xref-info* $DEBUG)
(load "garnet-loader")
(load "garnet-compiler")
$QUIT
EOF

[ $? -eq 0 ] && $LOAD << EOF

(require :clx)
(defvar Garnet-Garnet-Debug $DEBUG) ; debugging version
(load "garnet-loader")
(let ((args (list "$IMAGE"
                  #+sbcl :executable #+sbcl t
                  #+cmu :executable #+cmu t
                  #+ccl :prepend-kernel #+ccl t)))
(apply #'opal:make-image args))
#+allegro $QUIT
EOF
