\input texinfo  @c -*-texinfo-*-

@c Used for editorial markup.
@rmacro redtext{text}
@tex
  \\def\\rgbMyRed{1 0 0}
  \\def\\maincolor{\\rgbMyRed}
  \\pdfsetcolor{\\maincolor}
@end tex

\text\

@tex
  \\def\\rgbMyBlack{0 0 0}
  \\def\\maincolor{\\rgbMyBlack}
  \\pdfsetcolor{\\maincolor}
@end tex

@end rmacro

@c %**start of header

@settitle Garnet Reference and User Manual

@c %**end of header

@c See two-volume-cross-refs.txt.

@include garnetver.texi
@include garnetmanualver.texi
@include garnetmanualdate.texi

@c Combine indices.
@c @synindex cp fn
@c @syncodeindex vr fn
@c @syncodeindex ky fn
@c @syncodeindex pg fn
@c We use the "type index" to index new functions and variables.
@c @syncodeindex tp fn

@copying
This is edition @value{VERSION} of the @cite{Garnet Reference and User Manual},@*
corresponding to Garnet version @value{GARNETVER}.

Copyright @copyright{} 19xx--2020

@end copying

@dircategory Garnet
@direntry
* Garnet: (garnet).               Garnet.
@end direntry

@titlepage
@title Garnet Reference and User Manual
@subtitle For Garnet Version @value{GARNETVER}
@subtitle Revision @value{VERSION}, @value{DATE}

@page
@vskip 0pt plus 1filll
@insertcopying

@sp 2

@sp 2
@end titlepage


@c Print the tables of contents
@summarycontents
@contents


@ifnottex
@node Top
@top Emacs Lisp


@insertcopying
@end ifnottex

@c Note Texinfo menu system remains to be done.

@menu
* Introduction::            Introduction and conventions used.

* Lisp Data Types::         Data types of objects in Emacs Lisp.
* Numbers::                 Numbers and arithmetic functions.
* Strings and Characters::  Strings, and functions that work on them.
* Lists::                   Lists, cons cells, and related functions.
* Sequences Arrays Vectors::  Lists, strings and vectors are called sequences.
                                Certain functions act on any kind of sequence.
                                The description of vectors is here as well.
* Packaging::               Preparing Lisp code for distribution.

Appendices

* Antinews::                Info for users downgrading to Emacs 26.
* GNU Free Documentation License:: The license for this documentation.
* GPL::                     Conditions for copying and changing GNU Emacs.
* Tips::                    Advice and coding conventions for Emacs Lisp.
* GNU Emacs Internals::     Building and dumping Emacs;
                              internal data structures.
* Standard Errors::         List of some standard error symbols.
* Standard Keymaps::        List of some standard keymaps.
* Standard Hooks::          List of some standard hook variables.

* Index::                   Index including concepts, functions, variables,
                              and other terms.

@ignore
* New Symbols::             New functions and variables in Emacs @value{EMACSVER}.
@end ignore

@c Do NOT modify the following 3 lines!  They must have this form to
@c be correctly identified by 'texinfo-multiple-files-update'.  In
@c particular, the detailed menu header line MUST be identical to the
@c value of 'texinfo-master-menu-header'.  See texnfo-upd.el.

@detailmenu
 --- The Detailed Node Listing ---
 ---------------------------------

Here are other nodes that are subnodes of those already listed,
mentioned here so you can get to them in one step:

Modifying Existing List Structure

* Setcar::                  Replacing an element in a list.
* Setcdr::                  Replacing part of the list backbone.
                              This can be used to remove or add elements.
* Rearrangement::           Reordering the elements in a list; combining lists.

Property Lists

* Plists and Alists::       Comparison of the advantages of property
                              lists and association lists.
* Plist Access::            Accessing property lists stored elsewhere.

Object Internals

* Buffer Internals::        Components of a buffer structure.
* Window Internals::        Components of a window structure.
* Process Internals::       Components of a process structure.
@end detailmenu
@end menu

@include overview.texi
@include tour.texi
@include tutorial.texi
@include kr.texi
@include opal.texi
@include inter.texi
@include aggregadgets.texi
@include gadgets.texi
@include debug.texi
@include demos.texi
@include sampleprog.texi
@include gilt.texi
@include c32.texi
@include lapidary.texi
@include hints.texi
@include gem.texi


@c @include(overview/garnetpapers.mss)
@c @include(creditetc.mss) x 12 (one for overview.texi, tour.texi, etc.)
@c @bibliography x 12 (one for overview.texi, tour.texi, etc.)

@c @include display.texi
@c @include os.texi

@c @include package.texi

@c appendices

@appendix GNU General Public License

@include index.texi


@ignore
@node New Symbols
@unnumbered New Symbols Since the Previous Edition

@printindex tp
@end ignore

@bye

