(setf garnetdraw::*DRAW-AGG*
(create-instance 'FORMULAS OPAL:AGGREGADGET
  (:LEFT 0)
  (:TOP 0)
  (:WIDTH (o-formula (GVL :WINDOW :WIDTH) 680))
  (:HEIGHT (o-formula (GVL :WINDOW :HEIGHT) 410))
  (:CONSTANT `(:COMPONENTS ))
  (:FUNCTION-FOR-OK NIL)
  (:EXPORT-P T)
  (:WINDOW-TITLE "FORMULAS FIGURE")
  (:PACKAGE-NAME "USER")
  (:WINDOW-HEIGHT 300)
  (:WINDOW-WIDTH 450)
  (:WINDOW-TOP 0)
  (:WINDOW-LEFT 0)
  (:parts `(
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:OLD-HEIGHT 31)
      (:OLD-WIDTH 130)
      (:OLD-TOP 31)
      (:OLD-LEFT 55)
      (:parts (
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 55))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 40))
          (:CONSTANT (:KNOWN-AS T ))
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 48)
          (:FRAC-TOP 40)
          (:FRAC-LEFT 55)
          (:STRING "POINT-1")
          (:BOX (55 40 3 3 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 109))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 31))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 31)
          (:FRAC-LEFT 109)
          (:GROW-P T)
          (:BOX (109 31 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 147))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 31))
          (:CONSTANT (:KNOWN-AS T ))
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 31)
          (:FRAC-LEFT 147)
          (:STRING ":y1 10")
          (:BOX (147 31 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 147))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 48))
          (:CONSTANT (:KNOWN-AS T ))
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 48)
          (:FRAC-LEFT 147)
          (:STRING ":y2 40")
          (:BOX (147 48 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT")))))
    (NIL ,OPAL:TEXT
      (:LEFT ,(o-formula (FIRST (GVL :BOX)) 26))
      (:TOP ,(o-formula (SECOND (GVL :BOX)) 144))
      (:CONSTANT (:KNOWN-AS T ))
      (:TEMP-BOX (18 148 48 14 ))
      (:DRAW-FUNCTION :COPY)
      (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
      (:FRAC-HEIGHT 14)
      (:FRAC-WIDTH 48)
      (:FRAC-TOP 144)
      (:FRAC-LEFT 26)
      (:STRING "POINT-1")
      (:BOX (26 144 48 14 ))
      (:BEHAVIORS NIL)
      (:GILT-REF "TYPE-TEXT"))
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:BOX (22 160 76 31 ))
      (:OLD-HEIGHT 31)
      (:OLD-WIDTH 76)
      (:OLD-TOP 160)
      (:OLD-LEFT 22)
      (:parts (
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 22))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 160))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (22 160 30 30 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 160)
          (:FRAC-LEFT 22)
          (:GROW-P T)
          (:BOX (22 160 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 60))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 160))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (60 160 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 160)
          (:FRAC-LEFT 60)
          (:STRING ":y1 10")
          (:BOX (60 160 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 60))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 177))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (60 177 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 177)
          (:FRAC-LEFT 60)
          (:STRING ":y2 40")
          (:BOX (60 177 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT")))))
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:HEY 0)
      (:BOX (22 216 118 37 ))
      (:OLD-HEIGHT 37)
      (:OLD-WIDTH 125)
      (:OLD-TOP 216)
      (:OLD-LEFT 22)
      (:parts (
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 22))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 217))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (22 217 30 30 ))
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 217)
          (:FRAC-LEFT 22)
          (:GROW-P T)
          (:BOX (22 217 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 56))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 226))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (56 226 11 14 ))
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 11)
          (:FRAC-TOP 226)
          (:FRAC-LEFT 56)
          (:STRING ":y")
          (:BOX (56 226 11 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 78))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 216))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (78 216 61 14 ))
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 61)
          (:FRAC-TOP 216)
          (:FRAC-LEFT 78)
          (:STRING "CACHED 25")
          (:BOX (78 216 61 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 78))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 239))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (78 239 62 14 ))
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 62)
          (:FRAC-TOP 239)
          (:FRAC-LEFT 78)
          (:STRING "VALID  yes")
          (:BOX (78 239 62 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:LINE
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-POINTS (68 233 8 6 ))
          (:FRAC-Y2 239)
          (:FRAC-X2 76)
          (:FRAC-Y1 233)
          (:FRAC-X1 68)
          (:Y2 ,(o-formula (FOURTH (GVL :POINTS)) 239))
          (:X2 ,(o-formula (THIRD (GVL :POINTS)) 76))
          (:Y1 ,(o-formula (SECOND (GVL :POINTS)) 233))
          (:X1 ,(o-formula (FIRST (GVL :POINTS)) 68))
          (:GROW-P T)
          (:LINE-P T)
          (:POINTS (68 233 76 239 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-LINE"))
        (NIL ,OPAL:LINE
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-POINTS (68 233 8 -6 ))
          (:FRAC-Y2 227)
          (:FRAC-X2 76)
          (:FRAC-Y1 233)
          (:FRAC-X1 68)
          (:Y2 ,(o-formula (FOURTH (GVL :POINTS)) 227))
          (:X2 ,(o-formula (THIRD (GVL :POINTS)) 76))
          (:Y1 ,(o-formula (SECOND (GVL :POINTS)) 233))
          (:X1 ,(o-formula (FIRST (GVL :POINTS)) 68))
          (:GROW-P T)
          (:LINE-P T)
          (:POINTS (68 233 76 227 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-LINE")))))
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:BOX (298 216 118 37 ))
      (:OLD-HEIGHT 37)
      (:OLD-WIDTH 118)
      (:OLD-TOP 216)
      (:OLD-LEFT 298)
      (:parts (
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 298))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 217))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (298 217 30 30 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 217)
          (:FRAC-LEFT 298)
          (:GROW-P T)
          (:BOX (298 217 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 332))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 226))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (332 226 11 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 11)
          (:FRAC-TOP 226)
          (:FRAC-LEFT 332)
          (:STRING ":y")
          (:BOX (332 226 11 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 354))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 216))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (354 216 61 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 61)
          (:FRAC-TOP 216)
          (:FRAC-LEFT 354)
          (:STRING "CACHED 25")
          (:BOX (354 216 61 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 354))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 239))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (354 239 62 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 62)
          (:FRAC-TOP 239)
          (:FRAC-LEFT 354)
          (:STRING "VALID  no")
          (:BOX (354 239 62 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:LINE
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-POINTS (344 233 8 6 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-Y2 239)
          (:FRAC-X2 352)
          (:FRAC-Y1 233)
          (:FRAC-X1 344)
          (:Y2 ,(o-formula (FOURTH (GVL :POINTS)) 239))
          (:X2 ,(o-formula (THIRD (GVL :POINTS)) 352))
          (:Y1 ,(o-formula (SECOND (GVL :POINTS)) 233))
          (:X1 ,(o-formula (FIRST (GVL :POINTS)) 344))
          (:GROW-P T)
          (:LINE-P T)
          (:POINTS (344 233 352 239 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-LINE"))
        (NIL ,OPAL:LINE
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-POINTS (344 233 8 -6 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-Y2 227)
          (:FRAC-X2 352)
          (:FRAC-Y1 233)
          (:FRAC-X1 344)
          (:Y2 ,(o-formula (FOURTH (GVL :POINTS)) 227))
          (:X2 ,(o-formula (THIRD (GVL :POINTS)) 352))
          (:Y1 ,(o-formula (SECOND (GVL :POINTS)) 233))
          (:X1 ,(o-formula (FIRST (GVL :POINTS)) 344))
          (:GROW-P T)
          (:LINE-P T)
          (:POINTS (344 233 352 227 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-LINE")))))
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:BOX (436 160 76 31 ))
      (:OLD-HEIGHT 31)
      (:OLD-WIDTH 76)
      (:OLD-TOP 160)
      (:OLD-LEFT 436)
      (:parts (
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 436))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 160))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (436 160 30 30 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 160)
          (:FRAC-LEFT 436)
          (:GROW-P T)
          (:BOX (436 160 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 474))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 160))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (474 160 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 160)
          (:FRAC-LEFT 474)
          (:STRING ":y1 0")
          (:BOX (474 160 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 474))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 177))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (474 177 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 177)
          (:FRAC-LEFT 474)
          (:STRING ":y2 60")
          (:BOX (474 177 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT")))))
    (NIL ,OPAL:TEXT
      (:LEFT ,(o-formula (FIRST (GVL :BOX)) 26))
      (:TOP ,(o-formula (SECOND (GVL :BOX)) 200))
      (:CONSTANT (:KNOWN-AS ))
      (:FRAC-HEIGHT 14)
      (:FRAC-WIDTH 48)
      (:FRAC-TOP 200)
      (:FRAC-LEFT 26)
      (:BOX (26 200 48 14 ))
      (:STRING "POINT-2")
      (:TEXT-P T)
      (:FONT ,OPAL:DEFAULT-FONT)
      (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE))
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:OLD-HEIGHT 44)
      (:OLD-WIDTH 133)
      (:OLD-TOP 213)
      (:OLD-LEFT 436)
      (:BOX (436 213 133 44 ))
      (:parts (
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 436))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 217))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (436 217 30 30 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 217)
          (:FRAC-LEFT 436)
          (:GROW-P T)
          (:BOX (436 217 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 470))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 226))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (470 226 11 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 11)
          (:FRAC-TOP 226)
          (:FRAC-LEFT 470)
          (:STRING ":y")
          (:BOX (470 226 11 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 492))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 216))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (492 216 61 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 61)
          (:FRAC-TOP 216)
          (:FRAC-LEFT 492)
          (:STRING "CACHED 30")
          (:BOX (492 216 61 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 492))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 239))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (492 239 62 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 62)
          (:FRAC-TOP 239)
          (:FRAC-LEFT 492)
          (:STRING "VALID  yes")
          (:BOX (492 239 62 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:LINE
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-POINTS (482 233 8 6 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-Y2 239)
          (:FRAC-X2 490)
          (:FRAC-Y1 233)
          (:FRAC-X1 482)
          (:Y2 ,(o-formula (FOURTH (GVL :POINTS)) 239))
          (:X2 ,(o-formula (THIRD (GVL :POINTS)) 490))
          (:Y1 ,(o-formula (SECOND (GVL :POINTS)) 233))
          (:X1 ,(o-formula (FIRST (GVL :POINTS)) 482))
          (:GROW-P T)
          (:LINE-P T)
          (:POINTS (482 233 490 239 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-LINE"))
        (NIL ,OPAL:LINE
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-POINTS (482 233 8 -6 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-Y2 227)
          (:FRAC-X2 490)
          (:FRAC-Y1 233)
          (:FRAC-X1 482)
          (:Y2 ,(o-formula (FOURTH (GVL :POINTS)) 227))
          (:X2 ,(o-formula (THIRD (GVL :POINTS)) 490))
          (:Y1 ,(o-formula (SECOND (GVL :POINTS)) 233))
          (:X1 ,(o-formula (FIRST (GVL :POINTS)) 482))
          (:GROW-P T)
          (:LINE-P T)
          (:POINTS (482 233 490 227 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-LINE"))
        (NIL ,GARNETDRAW::MOVING-RECT
          (:CONSTANT (:KNOWN-AS ))
          (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
                (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                      (:BLUE 0)
                      (:GREEN 0)
                      (:RED 0)))))
          (:FILLING-STYLE NIL)
          (:DRAW-FUNCTION :COPY)
          (:BOX (535 238 34 19 ))
          (:FRAC-LEFT 535)
          (:FRAC-TOP 238)
          (:FRAC-WIDTH 34)
          (:FRAC-HEIGHT 19)
          (:BEHAVIORS NIL)
          (:TEMP-BOX (535 238 34 19 )))
        (NIL ,GARNETDRAW::MOVING-RECT
          (:CONSTANT (:KNOWN-AS ))
          (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
                (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                      (:BLUE 0)
                      (:GREEN 0)
                      (:RED 0)))))
          (:FILLING-STYLE NIL)
          (:DRAW-FUNCTION :COPY)
          (:BOX (535 213 34 19 ))
          (:FRAC-LEFT 535)
          (:FRAC-TOP 213)
          (:FRAC-WIDTH 34)
          (:FRAC-HEIGHT 19)
          (:BEHAVIORS NIL)
          (:TEMP-BOX (535 213 34 19 ))))))
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:OLD-HEIGHT 40)
      (:OLD-WIDTH 129)
      (:OLD-TOP 216)
      (:OLD-LEFT 160)
      (:BOX (160 216 129 40 ))
      (:parts (
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 160))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 217))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (160 217 30 30 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 217)
          (:FRAC-LEFT 160)
          (:GROW-P T)
          (:BOX (160 217 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 194))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 226))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (194 226 11 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 11)
          (:FRAC-TOP 226)
          (:FRAC-LEFT 194)
          (:STRING ":y")
          (:BOX (194 226 11 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 216))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 216))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (216 216 61 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 61)
          (:FRAC-TOP 216)
          (:FRAC-LEFT 216)
          (:STRING "CACHED 25")
          (:BOX (216 216 61 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 216))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 239))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (216 239 62 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 62)
          (:FRAC-TOP 239)
          (:FRAC-LEFT 216)
          (:STRING "VALID  no")
          (:BOX (216 239 62 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:LINE
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-POINTS (206 233 8 6 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-Y2 239)
          (:FRAC-X2 214)
          (:FRAC-Y1 233)
          (:FRAC-X1 206)
          (:Y2 ,(o-formula (FOURTH (GVL :POINTS)) 239))
          (:X2 ,(o-formula (THIRD (GVL :POINTS)) 214))
          (:Y1 ,(o-formula (SECOND (GVL :POINTS)) 233))
          (:X1 ,(o-formula (FIRST (GVL :POINTS)) 206))
          (:GROW-P T)
          (:LINE-P T)
          (:POINTS (206 233 214 239 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-LINE"))
        (NIL ,OPAL:LINE
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-POINTS (206 233 8 -6 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-Y2 227)
          (:FRAC-X2 214)
          (:FRAC-Y1 233)
          (:FRAC-X1 206)
          (:Y2 ,(o-formula (FOURTH (GVL :POINTS)) 227))
          (:X2 ,(o-formula (THIRD (GVL :POINTS)) 214))
          (:Y1 ,(o-formula (SECOND (GVL :POINTS)) 233))
          (:X1 ,(o-formula (FIRST (GVL :POINTS)) 206))
          (:GROW-P T)
          (:LINE-P T)
          (:POINTS (206 233 214 227 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-LINE"))
        (NIL ,GARNETDRAW::MOVING-RECT
          (:CONSTANT (:KNOWN-AS ))
          (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
                (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                      (:BLUE 0)
                      (:GREEN 0)
                      (:RED 0)))))
          (:FILLING-STYLE NIL)
          (:DRAW-FUNCTION :COPY)
          (:BOX (255 237 34 19 ))
          (:FRAC-LEFT 255)
          (:FRAC-TOP 237)
          (:FRAC-WIDTH 34)
          (:FRAC-HEIGHT 19)
          (:BEHAVIORS NIL)
          (:TEMP-BOX (255 237 34 19 ))))))
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:OLD-HEIGHT 33)
      (:OLD-WIDTH 80)
      (:OLD-TOP 158)
      (:OLD-LEFT 160)
      (:parts (
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 160))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 160))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (160 160 30 30 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 160)
          (:FRAC-LEFT 160)
          (:GROW-P T)
          (:BOX (160 160 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 198))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 160))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (198 160 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 160)
          (:FRAC-LEFT 198)
          (:STRING ":y1 0")
          (:BOX (198 160 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 198))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 177))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (198 177 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 177)
          (:FRAC-LEFT 198)
          (:STRING ":y2 40")
          (:BOX (198 177 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,GARNETDRAW::MOVING-RECT
          (:CONSTANT (:KNOWN-AS ))
          (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
                (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                      (:BLUE 0)
                      (:GREEN 0)
                      (:RED 0)))))
          (:FILLING-STYLE NIL)
          (:DRAW-FUNCTION :COPY)
          (:BOX (193 158 47 19 ))
          (:FRAC-LEFT 193)
          (:FRAC-TOP 158)
          (:FRAC-WIDTH 47)
          (:FRAC-HEIGHT 19)))))
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:OLD-HEIGHT 33)
      (:OLD-WIDTH 81)
      (:OLD-TOP 160)
      (:OLD-LEFT 298)
      (:parts (
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 298))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 160))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (298 160 30 30 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 160)
          (:FRAC-LEFT 298)
          (:GROW-P T)
          (:BOX (298 160 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 336))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 160))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (336 160 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 160)
          (:FRAC-LEFT 336)
          (:STRING ":y1 0")
          (:BOX (336 160 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 336))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 177))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (336 177 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 177)
          (:FRAC-LEFT 336)
          (:STRING ":y2 60")
          (:BOX (336 177 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,GARNETDRAW::MOVING-RECT
          (:CONSTANT (:KNOWN-AS ))
          (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
                (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                      (:BLUE 0)
                      (:GREEN 0)
                      (:RED 0)))))
          (:FILLING-STYLE NIL)
          (:DRAW-FUNCTION :COPY)
          (:BOX (332 174 47 19 ))
          (:FRAC-LEFT 332)
          (:FRAC-TOP 174)
          (:FRAC-WIDTH 47)
          (:FRAC-HEIGHT 19)
          (:BEHAVIORS NIL)))))
    (NIL ,GARNETDRAW::MOVING-AGG
      (:CONSTANT (:KNOWN-AS :COMPONENTS ))
      (:OLD-HEIGHT 31)
      (:OLD-WIDTH 527)
      (:OLD-TOP 76)
      (:OLD-LEFT 53)
      (:parts (
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 53))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 85))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (53 85 48 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 48)
          (:FRAC-TOP 85)
          (:FRAC-LEFT 53)
          (:STRING "POINT-2")
          (:BOX (53 85 48 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:CIRCLE
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 107))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 76))
          (:WIDTH ,(o-formula (THIRD (GVL :BOX)) 30))
          (:HEIGHT ,(o-formula (FOURTH (GVL :BOX)) 30))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (107 76 30 30 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 30)
          (:FRAC-WIDTH 30)
          (:FRAC-TOP 76)
          (:FRAC-LEFT 107)
          (:GROW-P T)
          (:BOX (107 76 30 30 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-RECTANGLE"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 145))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 76))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (145 76 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 76)
          (:FRAC-LEFT 145)
          (:STRING ":parent POINT-1")
          (:BOX (145 76 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT"))
        (NIL ,OPAL:TEXT
          (:LEFT ,(o-formula (FIRST (GVL :BOX)) 145))
          (:TOP ,(o-formula (SECOND (GVL :BOX)) 93))
          (:CONSTANT (:KNOWN-AS T ))
          (:TEMP-BOX (145 93 38 14 ))
          (:DRAW-FUNCTION :COPY)
          (:LINE-STYLE ,OPAL:DEFAULT-LINE-STYLE)
          (:FRAC-HEIGHT 14)
          (:FRAC-WIDTH 38)
          (:FRAC-TOP 93)
          (:FRAC-LEFT 145)
          (:STRING ":y (formula '(floor (+ (gvl :parent :y1) (gvl :parent :y2)) 2))")
          (:BOX (145 93 38 14 ))
          (:BEHAVIORS NIL)
          (:GILT-REF "TYPE-TEXT")))))
    (NIL ,OPAL:CURSOR-MULTI-TEXT
      (:LEFT ,(o-formula (FIRST (GVL :BOX)) 16))
      (:TOP ,(o-formula (SECOND (GVL :BOX)) 60))
      (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
            (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                  (:BLUE 0)
                  (:GREEN 0)
                  (:RED 0)))))
      (:FONT ,(create-instance nil OPAL:FONT
            (:SIZE :LARGE)
            (:FACE :BOLD)))
      (:TEXT-P T)
      (:STRING "(a)")
      (:BOX (16 60 0 0 ))
      (:FRAC-LEFT 16)
      (:FRAC-TOP 60)
      (:FRAC-WIDTH 14)
      (:FRAC-HEIGHT 11))
    (NIL ,OPAL:CURSOR-MULTI-TEXT
      (:LEFT ,(o-formula (FIRST (GVL :BOX)) 490))
      (:TOP ,(o-formula (SECOND (GVL :BOX)) 123))
      (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
            (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                  (:BLUE 0)
                  (:GREEN 0)
                  (:RED 0)))))
      (:FONT ,(create-instance nil OPAL:FONT
            (:SIZE :LARGE)
            (:FACE :BOLD)))
      (:TEXT-P T)
      (:STRING "(e)")
      (:BOX (490 123 24 20 ))
      (:FRAC-LEFT 490)
      (:FRAC-TOP 123)
      (:FRAC-WIDTH 24)
      (:FRAC-HEIGHT 20)
      (:BEHAVIORS NIL)
      (:DRAW-FUNCTION :COPY)
      (:CURSOR-INDEX NIL)
      (:SAVED-CURSOR-INDEX 2))
    (NIL ,OPAL:CURSOR-MULTI-TEXT
      (:LEFT ,(o-formula (FIRST (GVL :BOX)) 345))
      (:TOP ,(o-formula (SECOND (GVL :BOX)) 123))
      (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
            (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                  (:BLUE 0)
                  (:GREEN 0)
                  (:RED 0)))))
      (:FONT ,(create-instance nil OPAL:FONT
            (:SIZE :LARGE)
            (:FACE :BOLD)))
      (:TEXT-P T)
      (:STRING "(d)")
      (:BOX (345 123 24 20 ))
      (:FRAC-LEFT 345)
      (:FRAC-TOP 123)
      (:FRAC-WIDTH 24)
      (:FRAC-HEIGHT 20)
      (:BEHAVIORS NIL)
      (:DRAW-FUNCTION :COPY)
      (:CURSOR-INDEX NIL)
      (:SAVED-CURSOR-INDEX 2))
    (NIL ,OPAL:CURSOR-MULTI-TEXT
      (:LEFT ,(o-formula (FIRST (GVL :BOX)) 212))
      (:TOP ,(o-formula (SECOND (GVL :BOX)) 123))
      (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
            (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                  (:BLUE 0)
                  (:GREEN 0)
                  (:RED 0)))))
      (:FONT ,(create-instance nil OPAL:FONT
            (:SIZE :LARGE)
            (:FACE :BOLD)))
      (:TEXT-P T)
      (:STRING "(c)")
      (:BOX (212 123 24 20 ))
      (:FRAC-LEFT 212)
      (:FRAC-TOP 123)
      (:FRAC-WIDTH 24)
      (:FRAC-HEIGHT 20)
      (:BEHAVIORS NIL)
      (:DRAW-FUNCTION :COPY)
      (:CURSOR-INDEX NIL)
      (:SAVED-CURSOR-INDEX 2))
    (NIL ,OPAL:CURSOR-MULTI-TEXT
      (:LEFT ,(o-formula (FIRST (GVL :BOX)) 69))
      (:TOP ,(o-formula (SECOND (GVL :BOX)) 123))
      (:LINE-STYLE ,(create-instance nil OPAL:LINE-STYLE
            (:FOREGROUND-COLOR (create-instance nil OPAL:COLOR
                  (:BLUE 0)
                  (:GREEN 0)
                  (:RED 0)))))
      (:FONT ,(create-instance nil OPAL:FONT
            (:SIZE :LARGE)
            (:FACE :BOLD)))
      (:TEXT-P T)
      (:STRING "(b)")
      (:BOX (69 123 24 20 ))
      (:FRAC-LEFT 69)
      (:FRAC-TOP 123)
      (:FRAC-WIDTH 24)
      (:FRAC-HEIGHT 20)
      (:BEHAVIORS NIL)
      (:DRAW-FUNCTION :COPY)
      (:CURSOR-INDEX NIL)
      (:SAVED-CURSOR-INDEX 2)))))

)
